<a href="https://colab.research.google.com/github/JanPelisek/dostupnost-JMK/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**EDA**

In [ ]:
import pandas as pd

In [ ]:
# Načtení dat. souborů do proměnných z Githubu
url = "https://raw.githubusercontent.com/JanPelisek/dostupnost-JMK/main/Data/"
seznam = ["zastavky_mhd.csv", "trasy_linek.csv", "stops.csv", "trips.csv",
          "routes.csv", "transfers.csv", "stop_times.csv", "polohy_vozidel.csv",
          "calendar_dates.csv", "calendar.csv", "api.csv", "agency.csv"]

for soubor in seznam:
  df = pd.read_csv(url + soubor)
  globals()[soubor[:-4]] = df


del df, seznam, soubor, url

Proměnné **bez významu** pro analýzu:

Níže uvedená data neobsahují informace nezbytné pro analýzu. Seznam bude aktualizován a proměnné nakonec odebrány včetně tohoto komentáře (ve finálním zpracování nebudou vůbec zmíněny)
- agency
- api
- stop_times

In [ ]:
# úprava datumu z typu integer na formát data YYYY-MM-DD


calendar["start_date"] = pd.to_datetime(calendar["start_date"],  format='%Y%m%d')
calendar["end_date"] = pd.to_datetime(calendar["end_date"],  format='%Y%m%d')
print(calendar.info())
display(calendar.describe())
calendar.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 485 entries, 0 to 484
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   service_id  485 non-null    int64
 1   monday      485 non-null    int64
 2   tuesday     485 non-null    int64
 3   wednesday   485 non-null    int64
 4   thursday    485 non-null    int64
 5   friday      485 non-null    int64
 6   saturday    485 non-null    int64
 7   sunday      485 non-null    int64
 8   start_date  485 non-null    datetime64[ns]
 9   end_date    485 non-null    datetime64[ns]
dtypes: datetime64[ns](2), int64(8)
memory usage: 38.0 KB
None

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
count,485.000000,485.000000,485.000000,485.000000,485.000000,485.000000,485.000000,485.000000,485,485
mean,243.000000,0.480412,0.470103,0.470103,0.470103,0.486598,0.503093,0.496907,2025-03-24 01:40:56.907216640,2025-05-22 11:28:49.484536064
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2025-03-03 00:00:00,2025-03-03 00:00:00
25%,122.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2025-03-08 00:00:00,2025-04-06 00:00:00
50%,243.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2025-03-15 00:00:00,2025-06-22 00:00:00
75%,364.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2025-03-30 00:00:00,2025-06-29 00:00:00
max,485.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2025-07-01 00:00:00,2025-07-01 00:00:00
std,140.151704,0.500132,0.499621,0.499621,0.499621,0.500336,0.500507,0.500507,NaN,NaN

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,1,1,1,1,1,1,0,0,2025-03-03,2025-06-30
1,2,1,1,1,1,1,0,0,2025-03-03,2025-06-30
2,3,1,1,1,1,1,0,0,2025-03-03,2025-03-03
3,4,1,1,1,1,1,0,0,2025-03-03,2025-06-27
4,5,1,1,1,1,1,0,0,2025-03-03,2025-04-30

In [ ]:
calendar_dates["date"] = pd.to_datetime(calendar_dates["date"],  format='%Y%m%d')
print(calendar_dates.info())
display(calendar_dates.describe())
calendar_dates.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4592 entries, 0 to 4591
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_id      4592 non-null   int64
 1   date            4592 non-null   datetime64[ns]
 2   exception_type  4592 non-null   int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 107.8 KB
None

        service_id                           date  exception_type
count  4592.000000                           4592     4592.000000
mean    179.280923  2025-04-30 02:37:44.111498240        1.931838
min       1.000000            2025-03-04 00:00:00        1.000000
25%      78.000000            2025-04-08 00:00:00        2.000000
50%     137.000000            2025-04-29 00:00:00        2.000000
75%     286.000000            2025-05-22 00:00:00        2.000000
max     483.000000            2025-06-28 00:00:00        2.000000
std     132.835486                            NaN        0.252051

   service_id       date  exception_type
0           1 2025-04-18               2
1           1 2025-04-21               2
2           1 2025-05-01               2
3           1 2025-05-08               2
4           2 2025-03-07               2

In [ ]:
# Odebrání nepotřebného sloupce: last_update

polohy_vozidel.info()
display(polohy_vozidel.describe())
polohy_vozidel.drop(["last_update"], axis = 1, inplace = True)
polohy_vozidel.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10000 non-null  int64
 1   line          10000 non-null  object
 2   route_id      10000 non-null  int64
 3   vehicle_type  10000 non-null  int64
 4   bearing       10000 non-null  int64
 5   delay         10000 non-null  int64
 6   longitude     10000 non-null  float64
 7   latitude      10000 non-null  float64
 8   last_update   10000 non-null  object
dtypes: float64(2), int64(5), object(2)
memory usage: 703.3+ KB

,id,route_id,vehicle_type,bearing,delay,longitude,latitude
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,13569.286300,3057.65640,2.590300,154.458000,0.71400,16.628921,49.158802
std,10735.408893,3233.72202,1.796599,105.645536,4.13813,0.252386,0.153574
min,1082.000000,10.00000,0.000000,-1.000000,0.00000,16.030636,47.000000
25%,2672.000000,306.00000,1.000000,45.000000,0.00000,16.563360,49.127391
50%,7717.000000,4011.00000,2.000000,135.000000,0.00000,16.608020,49.191463
75%,21712.000000,4024.00000,4.000000,225.000000,1.00000,16.662419,49.219439
max,31055.000000,24805.00000,5.000000,315.000000,387.00000,17.488886,49.632660

      id line  route_id  vehicle_type  bearing  delay  longitude   latitude
0  21226  405       405             4      315      0  16.491396  49.181545
1  21916  819       301             4        0      0  16.056721  48.851700
2  21780  231       206             4      270      0  16.753613  49.359200
3   1810    5      4016             0      135      0  16.598152  49.164429
4  31005   S2      4712             5      225      0  16.613419  49.190651

In [ ]:
routes.info()
display(routes.describe())
routes.drop(["agency_id"], axis = 1)
routes.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   route_id          348 non-null    object
 1   agency_id         348 non-null    int64
 2   route_short_name  348 non-null    object
 3   route_long_name   348 non-null    object
 4   route_type        348 non-null    int64
 5   route_color       348 non-null    object
 6   route_text_color  136 non-null    object
dtypes: int64(2), object(5)
memory usage: 19.2+ KB

       agency_id  route_type
count      348.0  348.000000
mean        99.0   32.589080
std          0.0  151.392901
min         99.0    0.000000
25%         99.0    3.000000
50%         99.0    3.000000
75%         99.0    3.000000
max         99.0  800.000000

,route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color
0,L104D99,99,104,Brno - Pohořelice - Vlasatice - Hrušovany nad ...,3,00E68C,NaN
1,L105D99,99,105,Brno - Modřice - Pohořelice - Pasohlávky - Dol...,3,00E68C,NaN
2,L106D99,99,106,Brno - Slavkov u Brna - Žarošice - Dražůvky - ...,3,00E68C,NaN
3,L107D99,99,107,Vyškov - Rousínov - Brno,3,00E68C,NaN
4,L108D99,99,108,Brno - Modřice - Pohořelice - Lechovice - Znojmo,3,00E68C,NaN

In [ ]:
stop_times.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type
0,1,4:32:00,4:32:00,U15775Z2,1,0,0
1,1,4:34:00,4:34:00,U15773Z2,2,3,3
2,1,4:39:00,4:39:00,U15627Z2,3,0,0
3,1,4:41:00,4:41:00,U15640Z2,4,0,0
4,1,4:43:00,4:43:00,U15639Z2,5,0,0

In [ ]:
stops.info()
stops.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10957 entries, 0 to 10956
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   stop_id              10957 non-null  object
 1   stop_name            10957 non-null  object
 2   stop_lat             10957 non-null  float64
 3   stop_lon             10957 non-null  float64
 4   zone_id              10957 non-null  int64
 5   location_type        10957 non-null  int64
 6   parent_station       7693 non-null   object
 7   wheelchair_boarding  10957 non-null  int64
 8   platform_code        508 non-null    object
dtypes: float64(2), int64(3), object(4)
memory usage: 770.5+ KB

,stop_id,stop_name,stop_lat,stop_lon,zone_id,location_type,parent_station,wheelchair_boarding,platform_code
0,U15775Z2,"Hevlín, škola",48.751285,16.380187,570,0,U15775N1,2,NaN
1,U15773Z2,"Hevlín, cihelna",48.761387,16.383460,570,0,U15773N2,2,NaN
2,U15627Z2,Hrabětice,48.796862,16.395222,560,0,U15627N3,2,NaN
3,U15640Z2,"Šanov, u mostu",48.799235,16.386832,560,0,U15640N4,2,NaN
4,U15639Z2,"Šanov, požární zbrojnice",48.802143,16.373927,560,0,U15639N5,2,NaN

In [ ]:
transfers.info()
transfers.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220964 entries, 0 to 220963
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   from_stop_id       220964 non-null  object
 1   to_stop_id         220964 non-null  object
 2   transfer_type      220964 non-null  int64
 3   min_transfer_time  220964 non-null  int64
 4   from_trip_id       213578 non-null  float64
 5   to_trip_id         213578 non-null  float64
 6   max_waiting_time   213578 non-null  float64
dtypes: float64(3), int64(2), object(2)
memory usage: 11.8+ MB

,from_stop_id,to_stop_id,transfer_type,min_transfer_time,from_trip_id,to_trip_id,max_waiting_time
0,U1003Z1,U1003Z2,2,180,NaN,NaN,NaN
1,U1003Z2,U1003Z1,2,180,NaN,NaN,NaN
2,U1004Z1,U1461Z1,2,240,NaN,NaN,NaN
3,U1004Z1,U1461Z2,2,240,NaN,NaN,NaN
4,U1004Z1,U1461Z3,2,240,NaN,NaN,NaN

In [ ]:
trasy_linek.info()
trasy_linek.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110250 entries, 0 to 110249
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   route_id   110250 non-null  int64
 1   longitude  110250 non-null  float64
 2   latitude   110250 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 2.5 MB

   route_id  longitude   latitude
0         1  16.635004  48.668136
1         1  16.634825  48.668136
2         1  16.634664  48.668185
3         1  16.634579  48.668229
4         1  16.634526  48.668296

In [ ]:
trips.info()
trips.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60169 entries, 0 to 60168
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   route_id               60169 non-null  object
 1   service_id             60169 non-null  int64
 2   trip_id                60169 non-null  int64
 3   trip_headsign          60169 non-null  object
 4   wheelchair_accessible  60169 non-null  int64
 5   block_id               6808 non-null   float64
 6   direction_id           60169 non-null  int64
 7   bikes_allowed          60169 non-null  int64
 8   exceptional            60169 non-null  int64
dtypes: float64(1), int64(6), object(2)
memory usage: 4.1+ MB

,route_id,service_id,trip_id,trip_headsign,wheelchair_accessible,block_id,direction_id,bikes_allowed,exceptional
0,L104D99,1,1,ÚAN Zvonařka,1,NaN,1,0,0
1,L104D99,1,2,"Laa an der Thaya, Therme",1,NaN,0,0,0
2,L104D99,1,3,"Pohořelice, náměstí",1,NaN,1,0,0
3,L104D99,1,4,"Laa an der Thaya, Therme",1,NaN,0,0,0
4,L104D99,1,5,ÚAN Zvonařka,1,NaN,1,0,0

In [ ]:
zastavky_mhd.info()
zastavky_mhd.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10817 entries, 0 to 10816
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   stop_id              10817 non-null  object
 1   stop_name            10817 non-null  object
 2   latitude             10817 non-null  float64
 3   longitude            10817 non-null  float64
 4   zone_id              10811 non-null  float64
 5   wheelchair_boarding  10817 non-null  object
dtypes: float64(3), object(3)
memory usage: 507.2+ KB

,stop_id,stop_name,latitude,longitude,zone_id,wheelchair_boarding
0,U7530Z2,Dolní nádraží,49.183292,16.615558,100.0,2\
1,U1011Z2,Autobusové nádraží,49.186417,16.617622,100.0,2\
2,U19012Z1,"Hodonín, STS",48.870733,17.116435,900.0,2\
3,U1146Z33,Hlavní nádraží,49.191850,16.613617,100.0,2\
4,U1146Z31,Hlavní nádraží,49.191815,16.613991,100.0,2\

In [ ]:
api.head()

    Linka/CVlaku = trip_id: 104/4 = 1
0   Linka/CVlaku = trip_id: 104/5 = 2
1  Linka/CVlaku = trip_id: 104/14 = 3
2  Linka/CVlaku = trip_id: 104/13 = 4
3  Linka/CVlaku = trip_id: 104/22 = 5
4  Linka/CVlaku = trip_id: 104/21 = 6

In [ ]:
agency.head()

,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone
0,99,"IDS JMK (Data from: KORDIS JMK, DPMB)",http://www.idsjmk.cz,Europe/Prague,cs,5 4317 4317